# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        MainWindow.setMinimumSize(QtCore.QSize(600, 400))
        MainWindow.setMaximumSize(QtCore.QSize(600, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.view_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.view_btn.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.view_btn.setObjectName("view_btn")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 40, 581, 331))
        self.stackedWidget.setObjectName("stackedWidget")
        self.view_page = QtWidgets.QWidget()
        self.view_page.setObjectName("view_page")
        self.label = QtWidgets.QLabel(parent=self.view_page)
        self.label.setGeometry(QtCore.QRect(250, 20, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.view_page)
        self.add_page = QtWidgets.QWidget()
        self.add_page.setObjectName("add_page")
        self.label_2 = QtWidgets.QLabel(parent=self.add_page)
        self.label_2.setGeometry(QtCore.QRect(240, 20, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.add_page)
        self.add_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_btn.setGeometry(QtCore.QRect(100, 10, 75, 23))
        self.add_btn.setObjectName("add_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Financial Manager"))
        self.view_btn.setText(_translate("MainWindow", "View"))
        self.label.setText(_translate("MainWindow", "View"))
        self.label_2.setText(_translate("MainWindow", "Add / Edit"))
        self.add_btn.setText(_translate("MainWindow", "Add / Edit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
